site_name: IBM Americas Select-territory Partner Market Launchpad
site_description: Enablement program for partners to upskill in priority products that solve specific customer challenges.
site_author: IBM Americas Service Engineering Lab
docs_dir: docs
repo_url: https://github.com/IBM/select-t-partner-market-launchpad
repo_name: partner-market-launchpad
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: carbon-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: carbon-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    logo: material/rocket-launch-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.follow

extra_css:
  - stylesheets/carbon.css

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Program:
    - Overview: program/overview.md
    - Intended Audience: program/audience.md
    - Mode of Conduct: program/mode-of-conduct.md
    - Partner Pipeline: program/partner-pipeline.md
    - Changelog: program/changelog.md

  - Track 1:
    - Introduction: tracks/track-01/index.md
    - Overview:
      - Market Landscape: tracks/track-01/theory/what-and-why.md
      - Products Introduction: tracks/track-01/theory/product-overview.md
    - Labs:
      - Lab Environment Setup: tracks/track-01/lab-environment-setup.md
      - Lab 101:
        - Domains:
          - HR:
            - HR Agent:
              - Details: tracks/track-01/labs/lab-101/hr/hr-agent/details.md
              - Lab Guide: tracks/track-01/labs/lab-101/hr/hr-agent/lab-guide.md
          - Retail:
            - Use Cases:
              - AI Powered customer service:
                - Details: tracks/track-01/labs/lab-101/retail/use-case-1/details.md
                - Lab Guide: tracks/track-01/labs/lab-101/retail/use-case-1/lab-guide.md
          - Legal:
            - Use Cases:
              - Contract Lifecycle Management:
                - Details: tracks/track-01/labs/lab-101/legal/use-case-1/details.md
                - Lab Guide: tracks/track-01/labs/lab-101/legal/use-case-1/lab-guide.md
              - Legal Document Repository:
                - Details: tracks/track-01/labs/lab-101/legal/use-case-2/details.md
                - Lab Guide: tracks/track-01/labs/lab-101/legal/use-case-2/lab-guide.md
          - Automobile:
            - Use Cases:
              - Vehicle Maintenance:
                - Details: tracks/track-01/labs/lab-101/automobile/use-case-1/details.md
                - Lab Guide: tracks/track-01/labs/lab-101/automobile/use-case-1/lab-guide.md
          - Financial Services:
            - Use Cases:
              - Use Case 1:
                - Details: tracks/track-01/labs/lab-101/financial-services/use-case-1/details.md
                - Lab Guide: tracks/track-01/labs/lab-101/financial-services/use-case-1/lab-guide.md
          - Insurance:
            - Use Cases:
              - Insurance broker assistant:
                - Details: tracks/track-01/labs/lab-101/insurance/use-case-1/details.md
                - Lab Guide: tracks/track-01/labs/lab-101/insurance/use-case-1/lab-guide.md
      - Lab 201:
        - Domains:
          - Financial Services:
            - Use Cases:
              - Wealth Manager:
                - Details: tracks/track-01/labs/lab-201/financial-services/wealth-manager/details.md
                - Lab Guide: tracks/track-01/labs/lab-201/financial-services/wealth-manager/lab-guide.md
          - Supply chain:
            - Use Cases:
              - Supply chain use case:
                - Details: tracks/track-01/labs/lab-201/supply-chain/use-case-1/details.md
                - Lab Guide: tracks/track-01/labs/lab-201/supply-chain/use-case-1/lab-guide.md
      - Lab 301:
        - Domains:
          - Legal:
            - Use Cases:
              - Document Processing:
                - Steps: tracks/track-01/labs/lab-301/legal/document-processing/details.md
                - Lab Guide: tracks/track-01/labs/lab-301/legal/document-processing/lab-guide.md
          - Financial Services:
            - Use Cases:
              - Self-service KYC:
                - Steps: tracks/track-01/labs/lab-301/financial-services/self-service-kyc/details.md
                - Lab Guide: tracks/track-01/labs/lab-301/financial-services/self-service-kyc/lab-guide.md
      - Lab 401:
        - Domains:
          - Retail:
            - Use Cases:
              - Vendor Risk:
                - Steps: tracks/track-01/labs/lab-401/retail/vendor-risk/details.md
                - Lab Guide: tracks/track-01/labs/lab-401/retail/vendor-risk/lab-guide.md
          - Financial Services:
            - Use Cases:
              - Financial analysis:
                - Steps: tracks/track-01/labs/lab-401/financial-services/financial-analysis/details.md
                - Lab Guide: tracks/track-01/labs/lab-401/financial-services/financial-analysis/lab-guide.md
    - Troubleshooting: tracks/track-01/troubleshooting.md
  - Track 2:
    # - Introduction: tracks/track-02/index.md
    - Introduction: stylesheets/coming-soon.md
    # - Theory:
    #   - Market Landscape: tracks/track-02/theory/what-and-why.md
    #   - Products Introduction: tracks/track-02/theory/product-overview.md
    # - Labs:
    #   - Lab Environment Setup: tracks/track-02/lab-environment-setup.md
    #   - Lab 101:
    #     - Overview: tracks/track-02/labs/lab-101/overview.md
    #     - Prerequisites: tracks/track-02/labs/lab-101/prerequisites.md
    #     - Steps: tracks/track-02/labs/lab-101/steps.md
    #     - Validation: tracks/track-02/labs/lab-101/validation.md
    #     - Recap: tracks/track-02/labs/lab-101/recap.md
    #   - Lab 201:
    #     - Overview: tracks/track-02/labs/lab-201/overview.md
    #     - Prerequisites: tracks/track-02/labs/lab-201/prerequisites.md
    #     - Steps: tracks/track-02/labs/lab-201/steps.md
    #     - Validation: tracks/track-02/labs/lab-201/validation.md
    #     - Recap: tracks/track-02/labs/lab-201/recap.md
    #   - Lab 301:
    #     - Overview: tracks/track-02/labs/lab-301/overview.md
    #     - Prerequisites: tracks/track-02/labs/lab-301/prerequisites.md
    #     - Steps: tracks/track-02/labs/lab-301/steps.md
    #     - Validation: tracks/track-02/labs/lab-301/validation.md
    #     - Recap: tracks/track-02/labs/lab-301/recap.md
    #   - Lab 401:
    #     - Overview: tracks/track-02/labs/lab-401/overview.md
    #     - Prerequisites: tracks/track-02/labs/lab-401/prerequisites.md
    #     - Steps: tracks/track-02/labs/lab-401/steps.md
    #     - Validation: tracks/track-02/labs/lab-401/validation.md
    #     - Recap: tracks/track-02/labs/lab-401/recap.md
    # - Troubleshooting: tracks/track-02/troubleshooting.md
  - Track 3:
    - Introduction: tracks/track-03/index.md
    - Maximo:
      - Introduction: tracks/track-03/maximo/index.md
      - Overview:
        - Market Landscape: tracks/track-03/theory/what-and-why.md
        - Products Introduction: tracks/track-03/theory/product-overview.md
      - Labs:
        - Lab Environment Setup: tracks/track-03/lab-environment-setup.md
        - Lab 101:
          - Maximo:
            - Use Cases:
              - Use Case 1:
                - Details: tracks/track-03/labs/lab-101/maximo/use-case-1/details.md
                - Lab Guide: tracks/track-03/labs/lab-101/maximo/use-case-1/lab-guide.md
              - Use Case 2:
                - Details: tracks/track-03/labs/lab-101/maximo/use-case-2/details.md
                - Lab Guide: tracks/track-03/labs/lab-101/maximo/use-case-2/lab-guide.md
        - Lab 201:
          - Maximo:
            - Use Cases:
              - Use Case 1:
                - Details: tracks/track-03/labs/lab-201/maximo/use-case-1/details.md
                - Lab Guide: tracks/track-03/labs/lab-201/maximo/use-case-1/lab-guide.md
        - Lab 301:
          - Maximo:
            - Use Cases:
              - Use Case 1:
                - Details: tracks/track-03/labs/lab-301/maximo/use-case-1/details.md
                - Lab Guide: tracks/track-03/labs/lab-301/maximo/use-case-1/lab-guide.md
        - Lab 401:
          - Maximo:
            - Use Cases:
              - Use Case 1:
                - Details: tracks/track-03/labs/lab-401/maximo/use-case-1/details.md
                - Lab Guide: tracks/track-03/labs/lab-401/maximo/use-case-1/lab-guide.md
      - Troubleshooting: tracks/track-03/troubleshooting.md
  - Track 4:
    # - Introduction: tracks/track-04/index.md
    - Introduction: stylesheets/coming-soon.md
    # - Theory:
    #   - Market Landscape: tracks/track-04/theory/what-and-why.md
    #   - Products Introduction: tracks/track-04/theory/product-overview.md
    # - Labs:
    #   - Lab Environment Setup: tracks/track-04/lab-environment-setup.md
    #   - Lab 101:
    #     - Overview: tracks/track-04/labs/lab-101/overview.md
    #     - Prerequisites: tracks/track-04/labs/lab-101/prerequisites.md
    #     - Steps: tracks/track-04/labs/lab-101/steps.md
    #     - Validation: tracks/track-04/labs/lab-101/validation.md
    #     - Recap: tracks/track-04/labs/lab-101/recap.md
    #   - Lab 201:
    #     - Overview: tracks/track-04/labs/lab-201/overview.md
    #     - Prerequisites: tracks/track-04/labs/lab-201/prerequisites.md
    #     - Steps: tracks/track-04/labs/lab-201/steps.md
    #     - Validation: tracks/track-04/labs/lab-201/validation.md
    #     - Recap: tracks/track-04/labs/lab-201/recap.md
    #   - Lab 301:
    #     - Overview: tracks/track-04/labs/lab-301/overview.md
    #     - Prerequisites: tracks/track-04/labs/lab-301/prerequisites.md
    #     - Steps: tracks/track-04/labs/lab-301/steps.md
    #     - Validation: tracks/track-04/labs/lab-301/validation.md
    #     - Recap: tracks/track-04/labs/lab-301/recap.md
    #   - Lab 401:
    #     - Overview: tracks/track-04/labs/lab-401/overview.md
    #     - Prerequisites: tracks/track-04/labs/lab-401/prerequisites.md
    #     - Steps: tracks/track-04/labs/lab-401/steps.md
    #     - Validation: tracks/track-04/labs/lab-401/validation.md
    #     - Recap: tracks/track-04/labs/lab-401/recap.md
    # - Troubleshooting: tracks/track-04/troubleshooting.md

  - Facilitator Guide:
    - Running the Program: facilitator/running-the-program.md
    - Session Planning: facilitator/session-planning.md
    - Lab Environment Setup: facilitator/lab-environment-setup.md
    - FAQ Handling: facilitator/faq-handling.md

  - Resources:
    - Further Reading: resources/further-reading.md
    - Glossary: resources/glossary.md
    - Support & Help: resources/support.md
